# scripts/test_telegram_batch.py

import aiohttp
import asyncio
import csv
import time
from datetime import datetime
import html

BOT_TOKEN = "7987599734:AAGJPPAwNo6lzlUxB6PenofWCPXKZ_u6t_0"
CHAT_ID = "715037900"  # Your Telegram chat ID
SEND_URL = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
LOGS_URL = "http://localhost:8001/recent-logs?limit=100"


timestamp_sent = datetime.utcnow().isoformat()
print("🚀 Sending queries...")

queries = [
"Lamitta Brushes Kit For Lash Lift",
"thuya sp cream",
"Do you have disposable silicone lash brow brushes (50 pieces) in stock?",
"Sculptor Eyebrow Mask BROMASS, 30ml",
"thuya pe cream",
"What's the price of enigma lash extension palette black 6 lines short length?",
"Noemi Lash Lift Super Sticky Strong Glue Balm 25g",
"ProBeauty Space 5 Sections Premium Mattress",
"What's the price of katya vinog silicone lash lift shields for bottom lashes 3 pairs?",
"Lash&go Straight Tweezer With Curve",
"Eyelid Isolation Tape (600Pcs/roll)",
"What's the price of browxenna® brow scrub 50g?",
"Thuya Brow Lamination Permanent Gel VEGAN - Step 1, 15ml",
"What's the price of browxenna® contour white paste for eyebrows mapping 10g?",
"Do you have enigma lash extension palette black 16 lines 0.07 in stock?",
"Tell me about thuya perming kit / brow lamination set",
"What's the price of thuya lash brow filler btx botox, 5ml?",
"What's the price of sculptor lash extension primer 15 ml?",
"Katya Vinog Sticky Lash Lift Shields For Bottom Lashes 1 pair",
"Do you have henna mixing measuring spoon in stock?",
"lash&amp cream",
"Tell me about katya vinog lash lift pads silicone shields 1 size - purple",
"What's the price of enigma lash extension palette black 6 lines - mix 13-16mm?",
"Noemi Like Lift 3 Nourish Lotion, 10ml",
"Do you have lamination baby brush 1pc in stock?",
"What's the price of katya vinog reusable under eye patches - black?",
"Mia Pro Lash Lift Silicone Shields Compensators",
"Enigma Light Lash Extension Palette Black 16 Lines 0.10",
"Mia Pro Lashes Lamitab Palette For Lash Lift",
"FreiAVIVER Conical Brush New York (10mm)",
"eyebrow  cream",
"henna mi cream",
"What's the price of browxenna® henna and dye remover 15ml?",
"What's the price of lamination baby brush 1pc?",
"Sculptor Refreshing Post-Wax Gel, 250ml",
"Tell me about lamitta laminator brush for lash lift",
"Do you have lash extension mirror in stock?",
"Tell me about emocean 4-zones memory foam pillow lash extension",
"Tell me about viplash makeup silk lashes - lashes in the city dubai",
"Tell me about disposable silicone lash brow brushes (50 pieces)",
"LeviSsime Lash Color (5 colors)",
"What's the price of thuya brow lamination permanent gel - step 1, 15ml?",
"Tell me about eyebrow wax wooden sticks (pack of 100)",
"Do you have thuya perming kit / brow lamination set in stock?",
"Do you have disposable lip applicators (pack of 50) in stock?",
"What's the price of disposable mini micro brushes (100 pieces)?",
"Do you have sculptor lash extension primer 15 ml in stock?",
"Noemi Lash And Brow Hybrid Dye Sachet Kit",
"What's the price of enigma curved 90 tweezer purple?",
"Tell me about eyelash extension patches (50 pieces)",
"Do you have thuya special dye solution - oxidant, 14ml (cream) in stock?",
"What's the price of browxenna® two-phase tonic for henna washing off 100ml?",
"What's the price of disposable silicone lash brow brushes (50 pieces)?",
"sculptor cream",
"What's the price of sculptor lash isolating tweezer #02?",
"glamcore cream",
"What's the price of browxenna® threading thread?",
"Eyelash Eyebrow Shampoo Foam Cleansing Brush",
"What's the price of sculptor lash extension palette black gift 18 lines 0.07?",
"Do you have sculptor lash brow guru tweezer in stock?",
"Bronsun Eyelash And Eyebrow Gel Dye",
"Lamitta Silicone Pad For Lash Lift",
"What's the price of henna tint brushes (set of 2)?",
"viplash  cream",
"Tell me about sculptor lash tweezer #06.1",
"Do you have katya vinog reusable under eye patches - black in stock?",
"Tell me about viplash makeup silk lashes - lashes in the city brazil",
"What's the price of browxenna® pre-waxing oil 100ml?",
"Do you have pink jade stone in stock?",
"What's the price of katya vinog lash lift pads silicone shields 1 size - purple?",
"Do you have browxenna® pre-waxing oil 100ml in stock?",
"Do you have browxenna® brow waxing system set in stock?",
"Tell me about lash brow brush in tube",
"Tell me about enigma curved new tweezer multicolor",
"Do you have thuya skin protector cream, 50 ml in stock?",
"Do you have browxenna® contour wrap brow pencil in stock?",
"FreiAVIVER Silicone Organizer For Lash Lift Artist",
"Tell me about henna tint brushes (set of 2)",
"ProBeauty Space 8 Sections Premium Mattress",
"Tell me about enigma volume tweezer - chameleon extra sharp",
"Tell me about browxenna® pre-waxing oil 100ml",
"FreiAVIVER Beveled Brush Monaco (5mm)",
"Enigma Light Mini L 45 Tweezer - Rose Gold",
"Tell me about sculptor lash lift glue",
"ROB Brow Fix And Filler",
"Tell me about freiaviver brow wax",
"What's the price of sculptor lash extension palette dark chocolate 28 lines 0.07?",
"What's the price of katya vinog lash lift pallete?",
"What's the price of browxenna® brow wax 60g?",
"FreiAVIVER Beveled Brush Amsterdam NEW (8mm)",
"What's the price of enigma curved new tweezer multicolor?",
"Make Up False Lash Fans 10D 0.07 Mix 8-12 5 Lines",
"Do you have thuya regenerating cream - step 3, 15ml in stock?",
"Tell me about henna refresh antibacterial thread - aloe",
"What's the price of disposable lip applicators (50 pieces)?",
"FreiAVIVER Silicone Shields Set 4 pairs",
"Tell me about sculptor lash brow guru tweezer",
"Sculptor Dye Oxidant, 50ml",
"What's the price of lash lift y tool?",
"What's the price of thuya special dye solution - oxidant , 50ml (cream)?",
"Tell me about browxenna® post wax solvent 100ml",
"Tell me about sculptor lash tweezer #08",
"Do you have thuya eyebrow bleaching solution, 15ml in stock?",
"Tell me about browxenna® henna and dye remover 15ml",
"Do you have sculptor lash lift glue in stock?",
"Do you have sculptor adhesive glue for lash extension - gold 5ml expiry 07.09.25 in stock?",
"lash ext cream",
"IC Factory Lash Lift Glue 5ml",
"Do you have browxenna® perfect bleach set in stock?",
"Thuya Brow Scrub 15ml",
"Tell me about lash extension mirror",
"What's the price of browxenna® mineral solution for henna mixing 50ml?",
"Beauty Eyes Adhesive Glue For Lash Extension - M 5 Ml",
"Thuya Regenerating Cream VEGAN – Step 3, 15ml",
"Tell me about browxenna® brow waxing system set",
"What's the price of glamcore riki skinny lighted make up mirror?",
"Do you have henna expert eyebrow ruler in stock?",
"Tell me about enigma glue bonder lash extension sealing 15ml",
"Do you have browxenna® brow wax 60g in stock?",
"FreiAVIVER Brush Set - 8 pieces",
"Glass Cup For Henna Dye Mixing New",
"Do you have sculptor lash extension palette dark chocolate 28 lines 0.07 in stock?",
"Do you have thuya note - thuya dye coloristics manual in stock?",
"Tell me about browxenna® perfect bleach set",
"What's the price of browxenna® contour wrap brow pencil?",
"Tell me about viplash lash extension mirror",
"Lash&amp;Go Lash Extension Cleanser 15ml",
"Enigma Light Straight A Tweezer - Rose Gold",
"What's the price of bespecial makeup lash fans 20d/0.07?",
"Enigma Lash Extension Cleanser 15ml",
"What's the price of sculptor adhesive glue for lash extension - gold 5ml expiry 07.09.25?",
"Do you have emocean pro light led ring lamp in stock?",
"What's the price of sculptor lash extension palette black 18 lines 0.05?",
"thuya re cream",
"Tell me about thuya lash brow filler btx botox, 5ml",
"Lamitta EYEDO Collaboration Fixer, Glue Balm For Lash Lift, 5g",
"Tell me about katya vinog reusable under eye patches-white",
"Freiaviver Hot Brow Wax Hearts 100g",
"What's the price of sculptor lash lift glue?",
"Tell me about enigma lash extension palette black 6 lines - mix 13-16mm",
"Do you have eyebrow wax wooden sticks (pack of 100) in stock?",
"Katya Vinog Reusable Sticky Eyepatches BOW - 1 pair",
"Lash&go Straight A-1 Tweezer",
"Do you have browxenna® brow scrub 50g in stock?",
"Enigma Light Mini L Tweezer - Rose Gold",
"Tell me about thuya special dye solution - oxidant, 14ml (cream)",
"ProBeauty Space Organizer",
"Tell me about lash extension tape",
"Tell me about lb lash brow regenerating concentrate botox",
"What's the price of enigma straight tweezer - purple metallic extra sharp?",
"What's the price of sculptor lash extension palette black 28 lines 0.07?",
"Tell me about sculptor lash extension palette black 28 lines 0.10",
"Sculptor Lash Silicone Shields Pads -Open Look",
"Sculptor Lash Lift/Dye Brush Creator",
"What's the price of sculptor lash tweezer #08?",
"Noemi PreDyed Thread Black, 20m",
"Tell me about enigma straight tweezer - purple metallic extra sharp",
"Tell me about thuya - tint dye kit (all 9 colours + cream oxidant)",
"Thuya Lash &amp; Brow Booster Gel - Extreme Growth",
"henna re cream",
"Tell me about sculptor shampoo foam cleanser festa 160ml",
"What's the price of thuya eyebrow bleaching solution, 15ml?",
"Shik dye bluish black",
"What's the price of katya vinog reusable under eye patches-white?",
"What's the price of lash&amp;go cream remover ariel 15g?",
"Lash&Go Lash Extension Palette Black 16 Lines 0.10",
"Lash Box 5 Palettes",
"Enigma Lash Extension Primer 15ml",
"Glue ring",
"Tell me about sculptor lash extension cleanser 15ml",
"What's the price of disposable nylon lash brow brushes (50 pieces)?",
"Lash&amp;Go Lash Extension Palette Black 16 Lines 0.07",
"Sculptor Lash Isolating Tweezer  01",
"Do you have thuya - tint dye kit (all 9 colours + cream oxidant) in stock?",
"Tell me about enigma curved 90 tweezer purple",
"Tell me about viplash makeup silk lashes - lashes in the city paris",
"What's the price of sculptor lash steel lift lamination tool?",
"Do you have lb lash brow regenerating concentrate botox in stock?",
"What's the price of freiaviver brow wax?",
"What's the price of browxenna shampoo foam?",
"Tell me about katya vinog reusable under eye patches - black",
"Make Up False Strip Lashes Model Y1015",
"LB lamination baby brush",
"Do you have sculptor lash extension palette black 28 lines 0.07 in stock?",
"Inlei - Lash Lift System",
"Do you have thuya eye make up remover with curcuma, 200ml in stock?",
"What's the price of thuya perming kit / brow lamination set?",
"What's the price of sculptor lash tweezer #06.1?",
"LeviSsime Lash Activator Oxidant",
"Tell me about sculptor lash extension palette dark chocolate 28 lines 0.10",
"Sculptor Lash extension palette Prizmatic Black 20 lines 0.07",
"Do you have thuya brow intensifier tinted gel dark in stock?",
"What's the price of sculptor lash brow pro tweezer?",
"FreiAVIVER Straight Brush Havana (8mm)",
"What's the price of enigma curved new tweezer black?",
"Tell me about eyelash extension glue holder palette",
"Tell me about enigma l new tweezer purple metallic extra sharp",
"Enigma Mini L 90 Tweezer",
"Do you have sculptor lash brow pro tweezer in stock?",
"Lash Shade Lash Lift Pads Silicone Shields NEW 4 pairs",
"Sculptor Eyelashes Cream Dye (3 colors), 15ml",
"Do you have enigma lash extension palette black 16 lines 0.10 in stock?",
"Do you have viplash lash extension mirror in stock?",
"Inlei Brow Lamination",
"What's the price of lash extension tape -transparent?",
"What's the price of viplash lash extension palette black 16 lines 0.15?",
"Do you have lash extension tape - ultra white breatheable in stock?",
"Do you have katya vinog lash lift pads silicone shields 1 size - purple in stock?",
"Tell me about browxenna® brow scrub 50g",
"Tell me about disposable lip applicators (50 pieces)",
"What's the price of freiaviver brow tweezer manually sharpened?",
"BrowXenna LUME' Hybrid Gel Tint For Brows",
"Do you have lamitta laminator brush for lash lift in stock?",
"ProBeauty Space Head Pillow",
"Noemi Brow Multi Use Powder Pencil",
"Sculptor Brow Shikon Power Concentrate - 2 sizes",
"What's the price of pallete for mixing dye with markers?",
"Tell me about enigma lash extension palette black 16 lines 0.05",
"LB Next Lash Lift Set NOT GLUE, 14ml",
"Tell me about thuya brow lamination neutralizer cream - step 2, 10 ml",
"Do you have sculptor lash extension palette dark chocolate 28 lines 0.10 in stock?",
"Do you have lash lift y tool in stock?",
"Tell me about bespecial makeup lash fans 10d/0.07",
"ROB Brow Fix And Shape Gel - Lamination Effect Ultra Strong",
"Tell me about emocean pro light led ring lamp",
"Tell me about viplash makeup silk lashes - lashes in the city moscow",
"What's the price of lb lash brow regenerating concentrate botox?",
"Do you have bespecial makeup lash fans 20d/0.07 in stock?",
"Do you have sculptor lash tweezer #06.1 in stock?",
"Tell me about pink jade stone",
"Do you have lash&amp;go lash extension primer 15ml in stock?",
"Do you have browxenna® post wax solvent 100ml in stock?",
"What's the price of lash extension tape - ultra white breatheable?",
"Enigma Mini L 45 Tweezer",
"thuya la cream",
"Tell me about enigma pro straight tweezer metallic",
"Tell me about henna expert eyebrow ruler",
"ProBeauty Space Comfort Under Knee Pillow "Neo"",
"Tell me about lash&amp;go lash extension primer 15ml",
"emocean  cream",
"Make Up False Strip Lashes Model 3DV43",
"What's the price of enigma pro straight tweezer metallic?",
"Do you have browxenna® henna set brunette #101 #102 #103 in stock?",
"Tell me about viplash makeup silk lashes - lashes in the city new york",
"Do you have eyelash extension patches (50 pieces) in stock?",
"What's the price of thuya filters - dye shades and mixes samples?",
"Do you have sculptor adhesive glue for lash extension - best 5 ml expiry 23.07.25 in stock?",
"Beauty Eyes Adhesive Glue For Lash Extension - F 5 Ml",
"Do you have freiaviver brow tweezer manually sharpened in stock?",
"Tell me about browxenna® brow wax 60g",
"Enigma Straight A Tweezer - Chameleon Extra Sharp",
"Do you have lash&amp;go lash lift lamination pads silicone shields in stock?",
"enigma l cream",
"What's the price of thuya note - thuya dye coloristics manual?",
"Sculptor Flexi Line Lash Lift Sachet",
"Do you have viplash makeup silk lashes - lashes in the city paris in stock?",
"Tell me about lash lift y tool",
"Nagaraku Lash Extension Palette Brown 16 lines",
"Do you have viplash tweezer hatchet steel in stock?",
"What's the price of browxenna® henna set brunette #101 #102 #103?",
"FreiAVIVER Beveled Brush Barcelona (6mm)",
"Tell me about lash extension tape -transparent",
"Do you have thuya brow intensifier tinted gel medium in stock?",
"Thuya Contour White Paste for Brow Mapping 15g",
"Do you have lash extension tape soft to skin in stock?",
"What's the price of pink jade stone?",
"What's the price of lash&amp;go lash lift lamination pads silicone shields?",
"What's the price of browxenna® wooden sticks / waxing spatulas?",
"thuya sk cream",
"Tell me about henna mixing measuring spoon",
"FreiAVIVER X Svetlana Vasiltsova Brow Brush Set (5 brushes)",
"Noemi hybrid dye set (10 colors plus oxidant)",
"What's the price of thuya special dye solution - oxidant, 14ml (cream)?",
"lamitta  cream",
"lb lash  cream",
"Do you have enigma straight tweezer - purple metallic extra sharp in stock?",
"Tell me about eyebrow cotton swabs (pack of 100)",
"ProBeauty Space Royal Velour Beauty Bed Cover",
"What's the price of bespecial brush cleaning pad?",
"Sculptor Lash Lift/Dye Straight Brush Artist",
"Tell me about thuya note - thuya dye coloristics manual",
"LB Lash Lift Y Tool",
"Do you have henna refresh antibacterial thread - aloe in stock?",
"Do you have lash extension tape in stock?",
"Make Up False Strip Lashes Model 3D38",
"What's the price of lamitta laminator brush for lash lift?",
"thuya fi cream",
"What's the price of sculptor adhesive glue for lash extension - black 5ml expiry 12.07.25?",
"Tell me about viplash lash extension palette black 16 lines 0.15",
"Do you have enigma glue bonder lash extension sealing 15ml in stock?",
"Tell me about sculptor lash extension palette black 28 lines 0.07",
"Lash&amp;Go Adhesive Glue for Lash Extension – Aurora 5 ml",
"Noemi Wax Heater Touch",
"What's the price of browxenna® pre-waxing lotion 100ml?",
"What's the price of viplash makeup silk lashes - lashes in the city new york?",
"Enigma Light Volume Tweezer - Rose Gold",
"katya vi cream",
"Sculptor Hot Brow Wax Flexion, 500g",
"FreiAVIVER Straight Brush Tokyo (10mm)",
"What's the price of eyelash extension glue holder palette?",
"What's the price of thuya eye make up remover with curcuma, 200ml?",
"Enigma Anti Remover Liquid 15ml",
"Do you have browxenna® contour white paste for eyebrows mapping 10g in stock?",
"Lash&Go Lash Extension Palette Black 16 Lines 0.05",
"Enigma Light Straight Tweezer - Rose Gold",
"Tell me about lamination baby brush 1pc",
"Freiaviver Silicone Mat for Beauty Artists",
"pallete  cream",
"Lamitta Laminator Slide Brush For Lash Lift",
"Do you have thuya special dye solution - oxidant , 50ml (cream) in stock?",
"enigma s cream",
"Do you have sculptor lash extension cleanser 15ml in stock?",
"Enigma Light Bent Isolation Tweezer - Rose Gold",
"Make Up False Lash Fans A Lash Type Mix 10-12 3 Lines",
"Do you have freiaviver brow wax in stock?",
"enigma g cream",
"Do you have emocean memory foam pillow lash extension in stock?",
"Lash&Go Brush for Steel Lift Lamination Tool 1 piece",
"Do you have enigma lash extension palette black 6 lines short length in stock?",
"What's the price of katya vinog lash lift pads silicone shields 6 pairs?",
"Enigma Lash Extension Palette Mokka Brown 16 Lines 0.07",
"Do you have thuya brow lamination neutralizer cream - step 2, 10 ml in stock?",
"Tell me about thuya skin protector cream, 50 ml",
"What's the price of enigma volume tweezer - chameleon extra sharp?",
"Tell me about enigma curved new tweezer black",
"What's the price of thuya brow lamination neutralizer cream - step 2, 10 ml?",
"Enigma Lash Extension Palette Black 16 lines 0.15 C 7-14 mix",
"Tell me about thuya eye make up remover with curcuma, 200ml",
"LB Lash Lift Glue 5ml",
"Thuya Lash Extension Cleansing Foam Mousse 50ml",
"FreiAVIVER Eyelash And Eyebrow Fixing Gel, 4ml",
"Do you have browxenna® perfect bleach bleaching powder 20g in stock?",
"Tell me about sculptor lash extension palette black 18 lines 0.05",
"Enigma Light Mini L 90 Tweezer - Rose Gold",
"laminati cream",
"thuya ey cream",
"What's the price of sculptor lash tweezer #07?",
"Do you have bespecial makeup lash fans 10d/0.07 in stock?",
"What's the price of lash extension mirror?",
"Enigma Lash Extension Cleansing Foam 50ml",
"Do you have thuya lash brow filler btx botox, 5ml in stock?",
"Sculptor Lash extension palette Prizmatic Black 20 lines 0.10",
"Do you have viplash makeup silk lashes - lashes in the city new york in stock?",
"What's the price of viplash tweezer hatchet steel?",
"Tell me about sculptor adhesive glue for lash extension - best 5 ml expiry 23.07.25",
"What's the price of enigma lash extension palette black 16 lines 0.10?",
"What's the price of viplash makeup silk lashes - lashes in the city brazil?",
"What's the price of disposable lip applicators (pack of 50)?",
"Bronsun Brow Lift Set",
"Tell me about disposable nylon lash brow brushes (50 pieces)",
"What's the price of thuya brow intensifier tinted gel dark?",
"LB Brow Therapy Caring Oil",
"Do you have browxenna® mineral solution for henna mixing 50ml in stock?",
"Lash&go Straight Tweezer",
"Lash&amp;go gel remover",
"Tell me about bespecial brush cleaning pad",
"Tell me about thuya brow intensifier tinted gel medium",
"Thuya Henna And Dye Color Remover, 100ml",
"Do you have glamcore riki skinny lighted make up mirror in stock?",
"BrowXenna - Henna 10ml",
"Katya Vinog Reusable Sticky Eyepatches BOW - 1 pair BLACK",
"disposab cream",
"Tell me about browxenna shampoo foam",
"Katya Vinog Reusable Sticky Eyepatches BOB - 1 pair",
"Tell me about enigma lash extension palette black 6 lines short length",
"Do you have sculptor adhesive glue for lash extension - black 5ml expiry 12.07.25 in stock?",
"What's the price of thuya brow intensifier tinted gel soft?",
"bespecia cream",
"Katya Vinog Lash Lift Silicone Shields Compensators 3 pairs",
"Do you have browxenna shampoo foam in stock?",
"Lash&amp;Go Lash Lift Glue 5ml",
"Bronsun Filters - Dye Shades And Mixes Samples",
"Bespecial Slimliner Eyebrow Ultra Thin Pencil",
"Do you have browxenna® wooden sticks / waxing spatulas in stock?",
"Tell me about sculptor lash extension palette dark chocolate 28 lines 0.07",
"What's the price of enigma lash extension palette black 16 lines 0.07?",
"Do you have pallete for mixing dye with markers in stock?",
"What's the price of browxenna® enzyme brow scrub 50g?",
"enigma c cream",
"Tell me about browxenna® perfect bleach bleaching powder 20g",
"What's the price of eyebrow cotton swabs (pack of 100)?",
"Do you have eyelash extension glue holder palette in stock?",
"Do you have disposable nylon lash brow brushes (50 pieces) in stock?",
"Levissime Filters - Dye Shades And Mixes Samples",
"Do you have enigma curved 90 tweezer purple in stock?",
"What's the price of emocean pro light led ring lamp?",
"Do you have sculptor lash tweezer #08 in stock?",
"Tell me about viplash tweezer hatchet steel",
"Do you have bespecial eyebrow brush - henna in stock?",
"Do you have enigma curved new tweezer black in stock?",
"What's the price of emocean memory foam pillow lash extension?",
"What's the price of browxenna® henna colour chart all shades?",
"Tell me about sculptor lash steel lift lamination tool",
"What's the price of browxenna® brow waxing system set?",
"ProBeauty Space Body Bend Mattress",
"What's the price of viplash makeup silk lashes - lashes in the city moscow?",
"henna ti cream",
"Browxenna Mono Step Lamination - Formula For Express lamination of eyebrows and eyelashes",
"Do you have enigma lash extension palette black 16 lines 0.05 in stock?",
"Do you have sculptor lash tweezer #07 in stock?",
"Tell me about sculptor lash extension palette black gift 18 lines 0.07",
"Noemi Henna And Dye Remover, 50ml",
"lash bro cream",
"Tell me about lash&amp;go cream remover ariel 15g",
"eyelash  cream",
"What's the price of browxenna® ruler with a stretched thread?",
"Do you have lash&amp;go cream remover ariel 15g in stock?",
"What's the price of henna refresh antibacterial thread - aloe?",
"Do you have enigma lash extension palette black 16 lines 0.12 in stock?",
"Tell me about browxenna® pre-waxing lotion 100ml",
"Noemi Redness Neutralizer 20g",
"What's the price of sculptor shampoo foam cleanser festa 160ml?",
"Tell me about browxenna® contour white paste for eyebrows mapping 10g",
"Do you have sculptor lash extension palette black 28 lines 0.10 in stock?",
"Ultra Thin Angled Brush",
"henna ex cream",
"lash lif cream",
"Tell me about browxenna® contour wrap brow pencil",
"Thuya Perming Kit / Brow Lamination Set VEGAN",
"Katya Vinog Lash Lift Pads Silicone Shields 1 size - Blue",
"Tell me about browxenna® post-waxing oil  100ml",
"Tell me about sculptor adhesive glue for lash extension - gold 5ml expiry 07.09.25",
"What's the price of eyebrow wax wooden sticks (pack of 100)?",
"Do you have enigma l new tweezer purple metallic extra sharp in stock?",
"Tell me about lash extension tape - ultra white breatheable",
"Enigma Mini L 90 Tweezer New",
"What's the price of enigma lash extension palette black 16 lines 0.05?",
"pink jad cream",
"Tell me about freiaviver brow tweezer manually sharpened",
"Tell me about thuya regenerating cream - step 3, 15ml",
"Tell me about sculptor adhesive glue for lash extension - black 5ml expiry 12.07.25",
"FreiAVIVER Eyelash And Eyebrow Botox, 10ml",
"What's the price of henna mixing measuring spoon?",
"Do you have henna tint brushes (set of 2) in stock?",
"What's the price of thuya brow intensifier tinted gel medium?",
"enigma v cream",
"Enigma Lash Extension Cleansing Foam PH 8, 120ml",
"Tell me about disposable lip applicators (pack of 50)",
"FreiAVIVER Beveled Brush Moscow (10mm)",
"Do you have lash brow brush in tube in stock?",
"Noemi Shampoo Foam, 50ml",
"Do you have lash extension tape -transparent in stock?",
"ProBeauty Space Vinyl Mattress Protection",
"Tell me about sculptor lash tweezer #07",
"Noemi Brow Primer, 50ml",
"Tell me about browxenna® wooden sticks / waxing spatulas",
"Glue holder pallets 50 pcs",
"Noemi Lash And Brow Lift Sachet",
"Do you have browxenna® pre-waxing lotion 100ml in stock?",
"What's the price of browxenna® perfect bleach set?",
"Do you have sculptor shampoo foam cleanser festa 160ml in stock?",
"What's the price of thuya skin protector cream, 50 ml?",
"thuya br cream",
"Freiaviver Contour Paste For Brow Mapping 10g",
"Noemi Premium silicone pads for lash lift (4 pairs)",
"Do you have browxenna® enzyme brow scrub 50g in stock?",
"Lamination Film 42mm *200m",
"Mia Pro Lashes Silicone Eyepatches",
"Do you have viplash lash extension palette black 16 lines 0.10 in stock?",
"Do you have katya vinog reusable under eye patches-white in stock?",
"Do you have browxenna® ruler with a stretched thread in stock?",
"Do you have sculptor lash isolating tweezer #02 in stock?",
"Tell me about thuya brow intensifier tinted gel dark",
"Sculptor Eyebrow Scrub BROMMAGE, 30ml",
"Bronsun Eyelash And Eyebrow Cream Dye",
"thuya no cream",
"Lash Shade Lash Lift Silicone Shields compensators",
"Sculptor Lash Tweezer  05",
"enigma p cream",
"Do you have viplash makeup silk lashes - lashes in the city moscow in stock?",
"Eyelash Extension Patches Ultra White (50 Pieces)",
"Tell me about thuya filters - dye shades and mixes samples",
"Tell me about lash&amp;go lash lift lamination pads silicone shields",
"What's the price of browxenna® post-waxing oil  100ml?",
"Bronsun Cream Developer Oxidant 3% 30ml",
"Do you have thuya brow lamination permanent gel - step 1, 15ml in stock?",
"Bottle Push Type 150 ml",
"What's the price of enigma glue bonder lash extension sealing 15ml?",
"What's the price of enigma lash extension palette black 16 lines 0.12?",
"What's the price of browxenna® post wax solvent 100ml?",
"Tell me about thuya eyebrow bleaching solution, 15ml",
"Noemi Brow Soap, 15g",
"Do you have eyebrow cotton swabs (pack of 100) in stock?",
"Enigma Mini Volume Tweezer Purple Metallic Extra Sharp",
"Tell me about browxenna® ruler with a stretched thread",
"Enigma Lash Extension Palette Mokka Brown 16 Lines 0.10",
"What's the price of sculptor lash extension palette black 28 lines 0.10?",
"Enigma Lash Extension Glue Accelerator Booster 15ml",
"What's the price of henna expert eyebrow ruler?",
"Lash&go L Tweezer",
"Noemi Mini Wax Heater Device",
"Do you have bespecial brush cleaning pad in stock?",
"What's the price of sculptor adhesive glue for lash extension - best 5 ml expiry 23.07.25?",
"Sculptor Lash Isolating Tweezer 03",
"Tell me about glamcore riki skinny lighted make up mirror",
"What's the price of lash&amp;go lash extension primer 15ml?",
"IC Factory Lash Lift",
"Do you have katya vinog lash lift pads silicone shields 6 pairs in stock?",
"thuya -  cream",
"Do you have thuya brow intensifier tinted gel soft in stock?"
]

async def send_query(session, query):
    payload = {
        "chat_id": CHAT_ID,
        "text": query
    }
    async with session.post(SEND_URL, json=payload) as resp:
        result = await resp.json()
        if not result.get("ok"):
            print(f"❌ Failed: {query[:30]}... → {result}")
        else:
            print(f"✅ Sent: {query[:30]}...")

async def send_all():
    async with aiohttp.ClientSession() as session:
        tasks = [send_query(session, q) for q in queries]
        await asyncio.gather(*tasks)

asyncio.run(send_all())

print("⏳ Waiting for bot replies...")
time.sleep(8)  # wait for bot to respond

print("📥 Fetching replies from /recent-logs...")
async def fetch_logs():
    async with aiohttp.ClientSession() as session:
        async with session.get(LOGS_URL) as resp:
            return await resp.json()

logs = asyncio.run(fetch_logs())

print("🧾 Logging results to CSV...")
rows = []

# Prepare a reply lookup dictionary
log_lookup = {}
for entry in logs:
    if entry["timestamp"] > timestamp_sent and entry["user_id"] == CHAT_ID:
        query = entry["query"]
        response = html.unescape(entry["response"])
        log_lookup[query.strip().lower()] = response.strip()

for q in queries:
    q_normalized = q.strip().lower()
    response = log_lookup.get(q_normalized, "— Not found —")
    rows.append({
        "Timestamp": timestamp_sent,
        "Query": q,
        "Status": "✅ Sent",
        "Bot Reply": response
    })

with open("batch_test_log.csv", "w", newline='', encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["Timestamp", "Query", "Status", "Bot Reply"])
    writer.writeheader()
    writer.writerows(rows)

print("✅ Done. Log saved to batch_test_log.csv")
